### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by trezona-lecomte** [astefanutti/decktape#104]
Hi there,

I installed decktape with `npm install -g decktape`, but attempting to run it produces a SyntaxError:
```
❯ decktape -h
/usr/local/lib/node_modules/decktape/decktape.js:154
(async () => {
       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```
Looks like I've installed decktape 2.0.3:
```
❯ npm list | ag decktape
     decktape@2.0.3
```
Thanks for your time, let me know if you need any more info.

**Comment by astefanutti** [comment]
Ah it's likely you use Node 6.x. I've used async / await which requires Node 7.6+. I should probably mention that is the requirements.

**Comment by trezona-lecomte** [comment]
Yup, upgrading `node` has fixed this issue, thanks a lot for the quick reply!
