### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by zmonoid** [astefanutti/decktape#112]
Error reports below:
```
100% exporting file 4/4
0% converting pdf 1/4
An error occurred during pdf conversion: Command failed: node /usr/lib/node_modules/backslide/node_modules/decktape/decktape.js -p 1000 file:///home/bzhou/Documents/slides/.tmp/pdf/index.html pdf/index.pdf
/usr/lib/node_modules/backslide/node_modules/decktape/decktape.js:160
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by astefanutti** [comment]
Ah it's likely you use Node 6.x. It uses async / await which requires Node 7.6+.

I'll try making it more explicit in the error message and should probably mention that is the requirements.

**Comment by zmonoid** [comment]
I have updated the newest version, but got new error:

```
0% converting pdf 1/4Error: spawn EACCES
    at _errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:493:9)
    at Function.launch (/usr/lib/node_modules/backslide/node_modules/puppeteer/lib/Launcher.js:81:40)
    at Function.launch (/usr/lib/node_modules/backslide/node_modules/puppeteer/lib/Puppeteer.js:25:21)
    at __dirname (/usr/lib/node_modules/backslide/node_modules/decktape/decktape.js:162:35)
    at Object.<anonymous> (/usr/lib/node_modules/backslide/node_modules/decktape/decktape.js:205:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)

An error occurred during pdf conversion: Command failed: node /usr/lib/node_modules/backslide/node_modules/decktape/decktape.js -p 1000 file:///home/bzhou/Documents/slides/.tmp/pdf/index.html pdf/index.pdf

```

**Comment by astefanutti** [comment]
For some reasons, it's a permission issue while starting the Chrome instance. Can you test using DeckTape directly, by running the following command:

    $ decktape file:///home/bzhou/Documents/slides/.tmp/pdf/index.html pdf/index.pdf

As you're using BackSlide, you may want to contact the BackSlide project as well.

**Comment by zmonoid** [comment]
Hi, it will report the same error:

```
Error: spawn EACCES
    at _errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:493:9)
    at Function.launch (/usr/lib/node_modules/decktape/node_modules/puppeteer/lib/Launcher.js:81:40)
    at Function.launch (/usr/lib/node_modules/decktape/node_modules/puppeteer/lib/Puppeteer.js:25:21)
    at __dirname (/usr/lib/node_modules/decktape/decktape.js:163:35)
    at Object.<anonymous> (/usr/lib/node_modules/decktape/decktape.js:206:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
'''

**Comment by astefanutti** [comment]
Could you indicate how you've installed DeckTape?

Could you try:

    $ sudo nom install -g decktape

Can you check the permissions of the `/usr/lib/node_modules/decktape` directory and make sure the user you use to start the command have proper access to it?

**Comment by zmonoid** [comment]
Yes, I installed it as 

``` sudo npm install -g decktape```

The access to the folder is given below:

```
 bzhou@bzhou-P57V6  /usr/lib/node_modules/decktape  ls -lh
total 44K
-rwxr-xr-x  1 bzhou bzhou  14K Sep 15 16:39 decktape.js
drwxr-xr-x  2 bzhou bzhou 4.0K Sep 15 17:09 libs
drwxr-xr-x 52 root  root  4.0K Sep 15 17:09 node_modules
-rw-r--r--  1 bzhou bzhou 1.5K Sep 15 17:09 package.json
drwxr-xr-x  2 bzhou bzhou 4.0K Sep 15 17:09 plugins
-rw-r--r--  1 bzhou bzhou  12K Sep  4 18:09 README.adoc
```

**Comment by astefanutti** [comment]
It seems your `/usr/lib/node_modules/decktape/node_modules` directory can only be accessed by root:

    drwxr-xr-x 52 root  root  4.0K Sep 15 17:09 node_modules

Which explain the error that you face.

You may need to modify your npm config our change the permission of the npm's default directory. See https://docs.npmjs.com/getting-started/fixing-npm-permissions.

**Comment by zmonoid** [comment]
Yes! It works!

Thank you!

**Comment by harmishhk** [comment]
I have the same issue while using decktape from astefanutti/decktape docker image.
