### ISSUE TITLE
Error: Kill ESRCH on Windows 10

### ISSUE THREAD

**Issue by pgrantmartello** [astefanutti/decktape#117]
I got this error: 

```
Error: kill ESRCH
    at exports._errnoException (util.js:1034:11)
    at process.kill (internal/process.js:188:13)
    at killChrome (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/puppeteer/lib/Launcher.js:122:19)
    at Function.launch (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/puppeteer/lib/Launcher.js:108:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

I don't know enough about Linux/CLI to be able to debug this myself. Any thoughts on what's happening?

**Comment by pgrantmartello** [comment]
This was on Windows 10 bash, btw.

**Comment by astefanutti** [comment]
I suspect this happens when Puppeteer tries to kill the Chrome instance.

It seems there is another error that's hidden by the error you've reported:
https://github.com/GoogleChrome/puppeteer/blob/433b17b5d28569a30b47ce894a3305cb192935ce/lib/Launcher.js#L108

Could you provide the exact command you use and the full log. I don't have a Windows 10 box so I won't be able to reproduce on my side unfortunately.

**Comment by pgrantmartello** [comment]
Okay, so here's what I found. I did not install globally, so my command was

```
 `npm bin`/decktape reveal / file
```
That's how I got the error. I'm not sure if this is the correct log, but it's the most recent I have:

[2017-10-13T13_18_59_742Z-debug.log](https://github.com/astefanutti/decktape/files/1382722/2017-10-13T13_18_59_742Z-debug.log)

I tried globally installing decktape to see if it would fix the issue for me, but the kill Chrome instance thing is probably happening because Puppeteer is failing to install Chrome at all:

```
ERROR: Failed to download Chromium r499413! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 503. URL: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/499413/chrome-linux.zip
```
[2017-10-13T13_27_14_123Z-debug.log](https://github.com/astefanutti/decktape/files/1382741/2017-10-13T13_27_14_123Z-debug.log)

So it looks like it's not your fault, nor Puppeteer's. Like I said, I don't know much about this CLI stuff. If I can get a headless chromium install for puppeteer, can I force it to use that one? Or that a question for their issues board?

**Comment by astefanutti** [comment]
Thanks for the details. It's surprising it tries to download the Linux binary while you're on Windows (maybe you use a subsystem...).

You can download Chrome separately and instruct Puppeteer to use it by passing the `--executablePath` option. DeckTape is actually forwarding that option so you can use it readily with DeckTape as well.

**Comment by pgrantmartello** [comment]
Yeah, it's bash on Windows which is actually a Linux subsystem. So once I have Chrome installed, I'm just doing
```
decktape --executablePath /path/to/chrome/ reveal / file
```
Is that right?

**Comment by astefanutti** [comment]
Yes. Mind that Puppeteer needs a compatible version of Chrome.

**Comment by pgrantmartello** [comment]
So you're right. I tried to run it with my local instance of Chrome and it came back and said "The only Chrome revision guaranteed to work is r499413", so I got that and moved the files to my local system. I tried two commands, both of which failed:

```
root@DESKTOP-V26FK16:/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js# `npm bin`/decktape --executablePath /mnt/c/Users/pgrant/chrome-linux/ reveal / file
Error: spawn EACCES
    at exports._errnoException (util.js:1034:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:378:9)
    at Function.launch (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/puppeteer/lib/Launcher.js:83:40)
    at Function.launch (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/puppeteer/lib/Puppeteer.js:25:21)
    at __dirname (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/decktape/decktape.js:164:35)
    at Object.<anonymous> (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/decktape/decktape.js:210:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

root@DESKTOP-V26FK16:/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js# `npm bin`/decktape --executablePath /mnt/c/Users/pgrant/chrome-linux/chrome reveal / file
Error: kill ESRCH
    at exports._errnoException (util.js:1034:11)
    at process.kill (internal/process.js:188:13)
    at killChrome (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/puppeteer/lib/Launcher.js:122:19)
    at Function.launch (/mnt/c/Users/pgrant/Documents/CSSDevConf/reveal.js/node_modules/puppeteer/lib/Launcher.js:108:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by astefanutti** [comment]
Could you just try starting that Chrome install directly from your Linux subsystem. I suspect it's not starting correctly in that context. Maybe an alternative for you would be to use the default Windows prompt.

**Comment by pgrantmartello** [comment]
No luck. I don't want to take any more of your time. I think I've given up :)

**Comment by astefanutti** [comment]
Thanks for the feedback. Maybe this is something you can report to the Puppeteer team so that they work on it.
