### ISSUE TITLE
Decktape throws "Error: spawn EACCES"

### ISSUE THREAD

**Issue by LaetitiaLoxo** [astefanutti/decktape#120]
Hi,

I used decktape once to send my slides in pdf mode and it was just perfect. Worked at once and result just as desired.

Then, a few month later, I tried it on another presentation and it won't work. So I tried on the very same presentation and it wouldn't work either...
I suspect it has something to do with a module I installed since which is named "external" (https://github.com/calevans/external), but I'm not sure.

Here is my log trace :

```
decktape myprez.html myprez.pdf
Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:378:9)
    at Function.launch (/usr/lib/node_modules/decktape/node_modules/puppeteer/lib/Launcher.js:83:40)
    at Function.launch (/usr/lib/node_modules/decktape/node_modules/puppeteer/lib/Puppeteer.js:25:21)
    at __dirname (/usr/lib/node_modules/decktape/decktape.js:164:35)
    at Object.<anonymous> (/usr/lib/node_modules/decktape/decktape.js:210:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Thanks for reading,

Lætitia

**Comment by LaetitiaLoxo** [comment]
Hey,

My mistake, I had completely forgotten I had resintalled it since last time.
After looking more closely, I found that permissions on some files where wrong.

Problem solved!

Have a nice day (ugt)!

Lætitia

**Comment by astefanutti** [comment]
I'm glad you find your way! Let me close this then 😉.
