### ISSUE TITLE
Installation problems on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by pabloab** [astefanutti/decktape#140]
I've just installed decktape@2.8.0 (`npm install -g decktape`) but I get:

    $ decktape
    /usr/local/lib/node_modules/decktape/decktape.js:178
    (async () => {
           ^
    SyntaxError: Unexpected token (
        at Object.exports.runInThisContext (vm.js:78:16)
        at Module._compile (module.js:543:28)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:420:7)
        at startup (bootstrap_node.js:139:9)
        at bootstrap_node.js:535:3
Please tell me if there is anything more I can do/provide to fix the problem.

**Comment by astefanutti** [comment]
It's likely you use a Node version that does not support async / await. DeckTape requires Node 7.10+. Could you try upgrading your Node install and give it a try?

**Comment by astefanutti** [comment]
Hum, it's clearly an unsupported async method error. It may be that the Node version picked up when executing `decktape` command is not the same as that of the `nodejs` command. It's hard to tell like that. One test would be to checkout this repository and then run `npm install` and `node decktape.js`.

**Comment by pabloab** [comment]
Same error running:
```
git clone https://github.com/astefanutti/decktape.git
cd decktape/
npm install
node decktape.js 
```
Maybe I need an even newer version of node?

**Comment by astefanutti** [comment]
If you could upgrade your Node install, that would definitely help.

On my side, I'll try reproducing locally with Node 7.10.

**Comment by astefanutti** [comment]
This works for me with Node 7.10.1.

**Comment by pabloab** [comment]
It seems DeckTape requires Node 8, [not just 7.10+](https://github.com/astefanutti/decktape/issues/140#issuecomment-378854310), as you said [because of `async`](https://stackoverflow.com/a/48571914/4970442). Solved [installing this way](https://askubuntu.com/a/480642/349837). Now with `decktape --size=1600x900 https://slides.com/username/deckname/fullscreen#/ deckname.pdf` everything works like a charm :-)
