### ISSUE TITLE
Installation problems on macOS High Sierra 10.13.4 

### ISSUE THREAD

**Issue by Junnie-Jobs** [astefanutti/decktape#141]
```
$ decktape
module.js:472
    throw err;
    ^

Error: Cannot find module './PDFRStreamForBuffer'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/decktape/node_modules/hummus/hummus.js:30:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
Please tell me if there is anything more I can do/provide to fix the problem.

**Comment by astefanutti** [comment]
Hummus is a native library so it may be you have compilation issues during installation. Could you double check? What version of Node do you use?

**Comment by Junnie-Jobs** [comment]
@astefanutti  Thanks for the quick answer. My Node version is v7.10.0

**Comment by Junnie-Jobs** [comment]
@astefanutti 
It is awesome. I solved the problem using the method you gave me. Thank you very much!
