### ISSUE TITLE
Installation issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by polarbear-tataki** [astefanutti/decktape#214]
Hi everyone,

I'm struggling for days to install DeckTape on my Ubuntu 18.04 computer, in aim to convert xaringan HTML5 presentations to pdf.

After several tries, I still have this error :

```
$ decktape -h
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/decktape/node_modules/puppeteer/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/decktape/node_modules/puppeteer/lib/BrowserFetcher.js:25:20)
```

What I have done:
```
$ sudo apt install curl
$ curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
```

Then:
```
$ sudo apt install -y nodejs
$ sudo apt install npm
```

I had an error with the package node-gyp (>= 0.10.9) so I reinstalled it:

    $ sudo apt-get install nodejs-dev node-gyp libssl1.0-dev

Then I installed npm and decktape as explained in the README file:

```
$ sudo apt-get install npm
$ npm install -g decktape
```

There were errors during the installation, so I cleaned the cache and ran again these lines and it seemed to work. But I do not find any solution for the error I mentioned upper.

Any ideas ?

Thanks

**Comment by astefanutti** [comment]
This should work with a newer version of NodeJS. Feel free to re-open this if needed.
