### ISSUE TITLE
Navigation timeout of 20000 ms exceeded

### ISSUE THREAD

**Issue by simonschoe** [astefanutti/decktape#225]
Hi there,

I am using docker to render [this presentation](https://simonschoe.github.io/introduction-to-the-tidyverse/#1) into PDF:

```
docker run --rm -t -v %cd%/desktop/.../slides:/slides astefanutti/decktape https://simonschoe.github.io/introduction-to-the-tidyverse/#1 index.pdf
```

Starting today, I am running into the following error:

```
TimeoutError: Navigation timeout of 20000 ms exceeded
    at /decktape/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/decktape/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:125:23)
    at async Frame.waitForNavigation (/decktape/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:429:16)
    at async Page.waitForNavigation (/decktape/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:836:16)
```

Any idea/advice is much appreciated!

**Comment by astefanutti** [comment]
It seems your presentation takes time to load. It is similar to #224. Ideally, an option should be added to allow passing longer timeout. In the meantime, the only option is to checkout the code locally and change the hard-coded value. Happy to accept a PR :).

**Comment by astefanutti** [comment]
Let me close this and track progress in #224.
