### ISSUE TITLE
Updating to decktape 3.11 caused panic

### ISSUE THREAD

**Issue by ssp2023** [astefanutti/decktape#320]
Running decktape 3.11 with this config- 
`"decktape", "automatic", htmlURL, pdfFile, "--chrome-path", "/usr/bin/google-chrome", "--chrome-arg=--no-sandbox"`

I get the following, rolling back to 3.10 fixes the issue. It's running node-20-alpine container.

`2024-01-03 22:10:00.493 PST Printing slide #4       (  4/ ?) ...
2024-01-03 22:10:03.204 PST Printing slide #5       (  5/ ?) ...TypeError: arg.executionContext is not a function at file:///usr/local/lib/node_modules/decktape/decktape.js:277:55
2024-01-03 22:10:03.204 PST
   at Array.map (<anonymous>)
2024-01-03 22:10:03.204 PST
   at file:///usr/local/lib/node_modules/decktape/decktape.js:277:40
2024-01-03 22:10:03.204 PST
   at file:///usr/local/lib/node_modules/decktape/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:1:242
2024-01-03 22:10:03.204 PST
   at Array.map (<anonymous>)
2024-01-03 22:10:03.204 PST
   at Object.emit (file:///usr/local/lib/node_modules/decktape/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:1:226)
2024-01-03 22:10:03.204 PST
   at CdpPage.emit (file:///usr/local/lib/node_modules/decktape/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:85:23)
2024-01-03 22:10:03.204 PST
   at #addConsoleMessage (file:///usr/local/lib/node_modules/decktape/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:665:14)
2024-01-03 22:10:03.204 PST
   at #onConsoleAPI (file:///usr/local/lib/node_modules/decktape/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:612:32)
2024-01-03 22:10:03.204 PST
   at file:///usr/local/lib/node_modules/decktape/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:1:242`

**Comment by astefanutti** [comment]
Thanks a lot for reporting the issue. By change, would you be able to share your presentation so I can reproduce on my end?

**Comment by ssp2023** [comment]
It's not on a public site but would the PDF help or any other way to
transfer it to you that can help.  response

Thanks for the quick response!

**Comment by astefanutti** [comment]
I would need the HTML presentation. No worries if it cannot be shared.
