### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by darribas** [astefanutti/decktape#344]
I _think_ this is not properly `decktape`, but it is an error I encounter when trying to install the library, and perhaps someone has come across a fix.

I try:

```
npm install decktape
```

And obtain:

```
jovyan@11fe68b04763:~$ npm install decktape

> puppeteer@22.12.1 postinstall /home/jovyan/node_modules/puppeteer
> node install.mjs

internal/modules/cjs/loader.js:819
  throw new ERR_REQUIRE_ESM(filename);
  ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/jovyan/node_modules/puppeteer/install.mjs
    at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:819:9)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
npm WARN enoent ENOENT: no such file or directory, open '/home/jovyan/package.json'
npm WARN ws@8.18.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.18.0 requires a peer of utf-8-validate@>=5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN cosmiconfig@9.0.0 requires a peer of typescript@>=4.9.5 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.18.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.18.0 requires a peer of utf-8-validate@>=5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN jovyan No description
npm WARN jovyan No repository field.
npm WARN jovyan No README data
npm WARN jovyan No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@22.12.1 postinstall: `node install.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@22.12.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jovyan/.npm/_logs/2024-08-05T22_17_55_764Z-debug.log
(gds) jovyan@11fe68b04763:~$ 
```

There seems to be an issue with the post-install, but I can't figure out any further detail. Any idea anyone? Thank you so much in advance!

**Comment by astefanutti** [comment]
Have you tried `npm install -g decktape`? You may need to install it globally if you're outside a Node package.

**Comment by darribas** [comment]
Forgot to mention, yes. Same outcome with the postinstall error :-(

**Comment by darribas** [comment]
Possibly! I do have node `v12.4.0`. Let me explore upgrading and see how things go. Will report back. THANK you so much for the pointer!

**Comment by darribas** [comment]
Confirmed, upgrading Node resolves the issue, closing. Thanks so much for the support!
